### ISSUE TITLE
What is the point of this addon?

### ISSUE THREAD

**Issue by aaronfranke** [mechPenSketch/hide_workspace#1]
You can already hide the 3D and Asset Library workspaces. Hiding 2D should be available in Godot 4.0.

![Screenshot from 2021-07-26 00-54-00](https://user-images.githubusercontent.com/1646875/126935392-d911af9c-e1de-46fd-9a08-8459afc9545a.png)

**Comment by mechPenSketch** [comment]
I did not expect hiding workspaces can be done via Editor > Manage Editor Features. I didn't look deep enough to see whether it's possible.

**Comment by mechPenSketch** [comment]
In the end I've made a few changes to justify this asset:
- It can hide 2D workspace when Godot currently can't.
- It can be used to more conveniently switch between different workspaces.
